DROP TABLE IF EXISTS billionaires;

CREATE TABLE ADDRESS
(
    STREET   VARCHAR(120),
    CITY     VARCHAR(64),
    POSTCODE VARCHAR(16),
    COUNTRY  VARCHAR(32),
    ID       INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE ORDER
(
    id             INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_TIME     DATE,
    DELIVERY       ADDRESS INTEGER,
    NUMBER_PILOTES INTEGER,
    ORDER_TOTAL    INTEGER,
    CLIENT         VARCHAR(20)
        FOREIGN KEY (USER) REFERENCES CLIENT(TELEPHONE)

);

CREATE TABLE CLIENT
(
    FIRST_NAME VARCHAR(64),
    LAST_NAME  VARCHAR(64),
    TELEPHONE  VARCHAR(20) PRIMARY KEY
);